import {Mongo} from 'meteor/mongo';
export const Profiles = new Mongo.Collection('profiles');
export const Programs = new Mongo.Collection('programs');
export const Lessons = new Mongo.Collection('lessons');
export const Websites = new Mongo.Collection('websites');
export const Companies = new Mongo.Collection('companies');
export const Trainers = new Mongo.Collection('trainers');
export const Athletes = new Mongo.Collection('athletes');
export const PurchasedPrograms = new Mongo.Collection('purchased_programs');
export const Events = new Mongo.Collection('events');
export const Products = new Mongo.Collection('products');
export const Exercises = new Mongo.Collection('exercises');
export const Items = new Mongo.Collection('items');
